"""Acorn color themes — semantic tokens + Textual CSS colors."""

THEMES = {
    'dark': {
        'name': 'dark',
        'icon': '🌰',
        # Backgrounds
        'bg': '#0e1117',
        'bg_header': '#161b22',
        'bg_input': '#161b22',
        'bg_panel': '#161b22',
        'fg': '#c9d1d9',
        'border': '#30363d',
        # Accents
        'accent': 'bright_cyan',
        'accent2': 'bright_magenta',
        'success': '#3fb950',
        'error': 'bold #f85149',
        'warning': '#d29922',
        'info': 'dim',
        'muted': '#8b949e',
        # Tools
        'tool_icon': '#d29922',
        'tool_done': '#3fb950',
        'read_icon': '#58a6ff',
        'edit_icon': '#d29922',
        'diff_add': '#3fb950',
        'diff_del': '#f85149',
        # Text styles
        'thinking': 'italic #58a6ff',
        'usage': '#8b949e',
        'prompt_user': '#58a6ff',
        'prompt_project': '#3fb950',
        'prompt_branch': '#d29922',
        'prompt_symbol': 'bold #58a6ff',
        # Bars
        'plan_bar_bg': 'white on #1f3a5f',
        'exec_bar_bg': 'black on #1a4d2e',
        'plan_bar_bg_dim': '#8b949e on #1f3a5f',
        'exec_bar_bg_dim': '#8b949e on #1a4d2e',
        'plan_label': 'bold white on #2d5a8e',
        'exec_label': 'bold white on #238636',
        # Other
        'banner': 'bold white',
        'banner_sub': '#8b949e',
        'code_theme': 'monokai',
        'separator': '#30363d',
    },
    'light': {
        'name': 'light',
        'icon': '🌰',
        'bg': '#ffffff',
        'bg_header': '#f6f8fa',
        'bg_input': '#f6f8fa',
        'bg_panel': '#f6f8fa',
        'fg': '#24292f',
        'border': '#d0d7de',
        'accent': '#0969da',
        'accent2': '#8250df',
        'success': '#1a7f37',
        'error': 'bold #cf222e',
        'warning': '#9a6700',
        'info': 'dim',
        'muted': '#656d76',
        'tool_icon': '#9a6700',
        'tool_done': '#1a7f37',
        'read_icon': '#0969da',
        'edit_icon': '#9a6700',
        'diff_add': '#1a7f37',
        'diff_del': '#cf222e',
        'thinking': 'italic #0969da',
        'usage': '#656d76',
        'prompt_user': '#0969da',
        'prompt_project': '#1a7f37',
        'prompt_branch': '#9a6700',
        'prompt_symbol': 'bold #0969da',
        'plan_bar_bg': 'white on #0969da',
        'exec_bar_bg': 'white on #1a7f37',
        'plan_bar_bg_dim': '#656d76 on #ddf4ff',
        'exec_bar_bg_dim': '#656d76 on #dafbe1',
        'plan_label': 'bold white on #0969da',
        'exec_label': 'bold white on #1a7f37',
        'banner': 'bold #24292f',
        'banner_sub': '#656d76',
        'code_theme': 'friendly',
        'separator': '#d0d7de',
    },
    'oak': {
        'name': 'oak',
        'icon': '🪵',
        'bg': '#1a1410',
        'bg_header': '#231c15',
        'bg_input': '#231c15',
        'bg_panel': '#231c15',
        'fg': '#d4c5a9',
        'border': '#4a3a28',
        'accent': '#d4a574',
        'accent2': '#8fbc8f',
        'success': '#8fbc8f',
        'error': 'bold #cd5c5c',
        'warning': '#daa520',
        'info': 'dim',
        'muted': '#8b8170',
        'tool_icon': '#daa520',
        'tool_done': '#8fbc8f',
        'read_icon': '#6b8e8e',
        'edit_icon': '#daa520',
        'diff_add': '#8fbc8f',
        'diff_del': '#cd5c5c',
        'thinking': 'italic #d4a574',
        'usage': '#8b8170',
        'prompt_user': '#d4a574',
        'prompt_project': '#8fbc8f',
        'prompt_branch': '#daa520',
        'prompt_symbol': 'bold #d4a574',
        'plan_bar_bg': '#d4c5a9 on #2e4a3e',
        'exec_bar_bg': '#d4c5a9 on #3e2e1a',
        'plan_bar_bg_dim': '#8b8170 on #2e4a3e',
        'exec_bar_bg_dim': '#8b8170 on #3e2e1a',
        'plan_label': 'bold #d4c5a9 on #3a6a50',
        'exec_label': 'bold #d4c5a9 on #5c3d1e',
        'banner': 'bold #d4a574',
        'banner_sub': '#8b8170',
        'code_theme': 'monokai',
        'separator': '#4a3a28',
    },
    'forest': {
        'name': 'forest',
        'icon': '🌲',
        'bg': '#0a1a0f',
        'bg_header': '#0f2415',
        'bg_input': '#0f2415',
        'bg_panel': '#0f2415',
        'fg': '#b8d4b8',
        'border': '#1e3a28',
        'accent': '#66cdaa',
        'accent2': '#98fb98',
        'success': '#98fb98',
        'error': 'bold #ff6b6b',
        'warning': '#ffd700',
        'info': 'dim',
        'muted': '#5a7a5a',
        'tool_icon': '#ffd700',
        'tool_done': '#98fb98',
        'read_icon': '#66cdaa',
        'edit_icon': '#ffd700',
        'diff_add': '#98fb98',
        'diff_del': '#ff6b6b',
        'thinking': 'italic #66cdaa',
        'usage': '#5a7a5a',
        'prompt_user': '#98fb98',
        'prompt_project': '#66cdaa',
        'prompt_branch': '#ffd700',
        'prompt_symbol': 'bold #98fb98',
        'plan_bar_bg': '#b8d4b8 on #1a3a2a',
        'exec_bar_bg': '#b8d4b8 on #2a4a1a',
        'plan_bar_bg_dim': '#5a7a5a on #1a3a2a',
        'exec_bar_bg_dim': '#5a7a5a on #2a4a1a',
        'plan_label': 'bold white on #2e6e4e',
        'exec_label': 'bold white on #3e7e2e',
        'banner': 'bold #98fb98',
        'banner_sub': '#5a7a5a',
        'code_theme': 'monokai',
        'separator': '#1e3a28',
    },
}

DEFAULT_THEME = 'dark'


def get_theme(name: str) -> dict:
    return THEMES.get(name, THEMES[DEFAULT_THEME])


def list_themes() -> list:
    return list(THEMES.keys())
