"""Acorn color themes — semantic tokens resolved by theme name."""

THEMES = {
    'dark': {
        'name': 'dark',
        'accent': 'bright_cyan',
        'accent2': 'bright_magenta',
        'success': 'green',
        'error': 'bold red',
        'warning': 'yellow',
        'info': 'dim',
        'muted': 'dim white',
        'tool_icon': 'yellow',
        'tool_done': 'green',
        'read_icon': 'blue',
        'edit_icon': 'yellow',
        'diff_add': 'green',
        'diff_del': 'red',
        'thinking': 'dim italic',
        'usage': 'dim',
        'prompt_user': 'bright_cyan',
        'prompt_project': 'bright_green',
        'prompt_branch': 'bright_yellow',
        'prompt_symbol': 'bold bright_white',
        'plan_bar_bg': 'bg:ansiblue fg:white',
        'exec_bar_bg': 'bg:ansigreen fg:black',
        'toolbar_hint': '',
        'banner': 'bold bright_white',
        'banner_sub': 'dim',
        'code_theme': 'monokai',
    },
    'light': {
        'name': 'light',
        'accent': 'dark_cyan',
        'accent2': 'dark_magenta',
        'success': 'dark_green',
        'error': 'bold dark_red',
        'warning': 'dark_orange3',
        'info': 'dim',
        'muted': 'grey50',
        'tool_icon': 'dark_orange3',
        'tool_done': 'dark_green',
        'read_icon': 'dark_blue',
        'edit_icon': 'dark_orange3',
        'diff_add': 'dark_green',
        'diff_del': 'dark_red',
        'thinking': 'dim italic',
        'usage': 'dim',
        'prompt_user': 'dark_cyan',
        'prompt_project': 'dark_green',
        'prompt_branch': 'dark_orange3',
        'prompt_symbol': 'bold black',
        'plan_bar_bg': 'bg:ansiblue fg:white',
        'exec_bar_bg': 'bg:ansigreen fg:black',
        'toolbar_hint': '',
        'banner': 'bold black',
        'banner_sub': 'dim',
        'code_theme': 'friendly',
    },
    'oak': {
        'name': 'oak',
        'accent': '#d4a574',
        'accent2': '#8fbc8f',
        'success': '#8fbc8f',
        'error': 'bold #cd5c5c',
        'warning': '#daa520',
        'info': 'dim',
        'muted': '#8b8682',
        'tool_icon': '#daa520',
        'tool_done': '#8fbc8f',
        'read_icon': '#6b8e8e',
        'edit_icon': '#daa520',
        'diff_add': '#8fbc8f',
        'diff_del': '#cd5c5c',
        'thinking': 'dim italic',
        'usage': 'dim',
        'prompt_user': '#d4a574',
        'prompt_project': '#8fbc8f',
        'prompt_branch': '#daa520',
        'prompt_symbol': 'bold #d4a574',
        'plan_bar_bg': 'bg:#2e4a3e fg:white',
        'exec_bar_bg': 'bg:#3e2e1a fg:#d4a574',
        'toolbar_hint': '',
        'banner': 'bold #d4a574',
        'banner_sub': '#8b8682',
        'code_theme': 'monokai',
    },
    'forest': {
        'name': 'forest',
        'accent': '#98fb98',
        'accent2': '#66cdaa',
        'success': '#98fb98',
        'error': 'bold #ff6b6b',
        'warning': '#ffd700',
        'info': 'dim',
        'muted': '#708090',
        'tool_icon': '#ffd700',
        'tool_done': '#98fb98',
        'read_icon': '#66cdaa',
        'edit_icon': '#ffd700',
        'diff_add': '#98fb98',
        'diff_del': '#ff6b6b',
        'thinking': 'dim italic',
        'usage': 'dim',
        'prompt_user': '#98fb98',
        'prompt_project': '#66cdaa',
        'prompt_branch': '#ffd700',
        'prompt_symbol': 'bold #98fb98',
        'plan_bar_bg': 'bg:#1a3a2a fg:white',
        'exec_bar_bg': 'bg:#2a4a1a fg:white',
        'toolbar_hint': '',
        'banner': 'bold #98fb98',
        'banner_sub': '#708090',
        'code_theme': 'monokai',
    },
}

DEFAULT_THEME = 'dark'


def get_theme(name: str) -> dict:
    return THEMES.get(name, THEMES[DEFAULT_THEME])


def list_themes() -> list:
    return list(THEMES.keys())
